_extends: probot-settings

project-board:
  name: 'Pipeline for QA'
  min-reviewers: 1
  tested-pr-label-name: 'Tested - Issues'
  contributor-column-name: 'CONTRIBUTOR'
  review-column-name: 'REVIEW'
  test-column-name: 'E2E Tests'

automated-tests:
  repo-full-name: 'status-im/status-react'
  job-full-name: 'status-react/e2e/status-app-prs'
  kickoff-column-name: 'E2E Tests'

github-team:
  slug: 'clojure'
